#!/bin/sh -e
# Note: the '-e' flag will make the script stop immediately upon error with 
# the error reflected in the environment.  This lets one issue commands like
# "./build sbitx && ./sbitx" to build then run if it built correctly, and not
# run if the build failed.
F=$1
O=$2
OPT=0
FLAGS="-g"
EXTRA_CFLAGS=""
MAIN_SRC="$F.c"

if [ "$F" = "jjbitxd" ]; then
    EXTRA_CFLAGS="-DJJ_HEADLESS_DAEMON=1"
    MAIN_SRC="sbitx.c"
fi
[ -z "$F" ] && {
   echo "usage:   $0 program [o|g|u]"
   echo "example: $0 sbitx"
   echo "-optional 'o' argument enables compiler optimizations"
   echo "-optional 'g' argument enables profile generation"
   echo "-optional 'u' argument enables usage of profile to guide optimizations"
   exit 1
}
if [ ! -z "$O" ] && [ "$O" = "o" ] ; then
	echo "!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!"
	echo "!! Building optimized binary, most warnings can be safely ignored !!"
	echo "!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!"
	FLAGS="-march=native -O3 -flto=auto"
	OPT=1
	rm -f *.gcda
fi
if [ ! -z "$O" ] && [ "$O" = "g" ] ; then
	rm -f *.gcda
	echo "!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!"
	echo "!! Building profile generating binary                             !!"
	echo "!! Run the application in your normal use case, then rerun with   !!"
	echo "!! the u option to generate a profile guided optimized build      !!"
	echo "!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!"
	FLAGS="-march=native -O3 -flto=auto -fprofile-generate"
fi
if [ ! -z "$O" ] && [ "$O" = "u" ] ; then
	echo "!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!"
	echo "!! Building profile guided binary                                 !!"
	echo "!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!"
	FLAGS="-march=native -O3 -flto=auto -fprofile-use"
	OPT=1
fi
WORKING_DIRECTORY=`pwd`
echo ">>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>"
date
mkdir -p "./audio"
mkdir -p "./data"
mkdir -p "./web"

if test -f "data/sbitx.db"; then
	echo "database is intact"
else
	echo "database doesn't exist, it will be created"
	cd data
	sqlite3 sbitx.db < create_db.sql
	cd ..
fi

if [ "$F" != "sbitx" ]; then
  echo "compiling $F in $WORKING_DIRECTORY"
else
  VERSION=`grep VER src/sdr_ui.h | awk 'FNR==1{print $4}' | sed -e 's/"//g'`
  echo "compiling $F version $VERSION in $WORKING_DIRECTORY"
fi
# Define Mongoose SSL flags - ensure OpenSSL is properly enabled
MONGOOSE_FLAGS="-DMG_ENABLE_OPENSSL=1 -DMG_ENABLE_MBEDTLS=0 -DMG_ENABLE_LINES=1 -DMG_TLS=MG_TLS_OPENSSL -DMG_ENABLE_SSI=0 -DMG_ENABLE_IPV6=0"

gcc $FLAGS $EXTRA_CFLAGS $MONGOOSE_FLAGS -o $F \
	 src/vfo.c src/sbitx_sound.c src/fft_filter.c src/sbitx_gtk.c src/sbitx_utils.c \
    src/i2cbb.c src/si5351v2.c src/ini.c src/hamlib.c src/queue.c src/modems.c src/logbook.c \
		src/modem_cw.c src/settings_ui.c src/hist_disp.c src/ntputil.c \
		src/telnet.c src/macros.c src/modem_ft8.c src/remote.c src/mongoose.c src/para_eq.c src/webserver.c src/eq_ui.c src/$MAIN_SRC  \
		src/ft8_lib/libft8.a  \
	-lwiringPi -lasound -lm -lfftw3 -lfftw3f -pthread -lncurses -lsqlite3 -lnsl -lrt -lssl -lcrypto \
	`pkg-config --cflags gtk+-3.0` `pkg-config --libs gtk+-3.0`
 
if [ $OPT -eq 1 ]; then
	#Remove debugging stuff for a smaller binary
	echo Stripping $F
	strip $F
fi

echo "Brought to you by the volunteer developer team at Radio&Elec Hub"
echo "<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<"
# This addition is used to provide the application the capability to adjust the local system time -W2JON
# CAP_SYS_NICE lets the audio thread acquire SCHED_FIFO real-time priority
# without running as root -- required since the ALSA period-size fix, or
# the audio thread silently falls back to normal scheduling.
# It should probably always run last at it'll fail if the file system doesn't support it - N1QM
# These are  combined to prevent the _last_ setting from being the only one effective 
if [ "$F" = "sbitx" ] && [ -x $F ]; then 
	# || : is a little hack to allow the script to continue if an error occurs - n1qm
	sudo setcap 'cap_sys_time+ep cap_sys_nice+eip' $F || :
fi
echo Build completed at $(date)
