#!/bin/sh -e
# Note: the '-e' flag will make the script stop immediately upon error with 
# the error reflected in the environment.  This makes it easier for users to
# see which command caused the error.
F=$@
echo ">>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>"
date
cd $HOME/sbitx
git stash --include-untracked
git remote set-url origin https://github.com/drexjj/zbitx.git
git stash
git pull
git checkout main
cd $HOME/sbitx/src/ft8_lib
make clean
make
cd $HOME/sbitx/
make clean
make
echo "<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<"

echo "zbitx software has been installed successfully. You can now close this window."
